-- ========================================
-- V4__Create_Quartz_Schema.sql
-- ========================================
-- Description: Quartz Scheduler schema for job management
-- Author: System
-- Date: 2025-10-29
-- Based on: Quartz 2.3.2+ for MySQL/InnoDB
-- ========================================

-- ===== Application Tables =====

-- Table: scheduled_job
-- Stores custom job metadata (application-specific)
CREATE TABLE IF NOT EXISTS scheduled_job (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    job_group VARCHAR(100) NOT NULL,
    job_class VARCHAR(255) NOT NULL,
    description TEXT,
    cron_expression VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    parameters TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    UNIQUE KEY uk_job_name_group (job_name, job_group),
    INDEX idx_job_status (status),
    INDEX idx_job_name_group (job_name, job_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Custom job metadata';

-- Table: job_execution_history
-- Stores job execution history and results
CREATE TABLE IF NOT EXISTS job_execution_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    job_id BIGINT NOT NULL,
    execution_time TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    duration_ms BIGINT,
    result TEXT,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_id) REFERENCES scheduled_job(id) ON DELETE CASCADE,
    INDEX idx_job_id (job_id),
    INDEX idx_execution_time (execution_time),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Job execution history';

-- ===== Quartz Internal Tables =====

-- Table: QRTZ_JOB_DETAILS
CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) DEFAULT NULL,
    JOB_CLASS_NAME VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP),
    INDEX idx_qrtz_j_req_recovery (SCHED_NAME, REQUESTS_RECOVERY),
    INDEX idx_qrtz_j_grp (SCHED_NAME, JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) DEFAULT NULL,
    NEXT_FIRE_TIME BIGINT(13) DEFAULT NULL,
    PREV_FIRE_TIME BIGINT(13) DEFAULT NULL,
    PRIORITY INTEGER DEFAULT NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT(13) NOT NULL,
    END_TIME BIGINT(13) DEFAULT NULL,
    CALENDAR_NAME VARCHAR(200) DEFAULT NULL,
    MISFIRE_INSTR SMALLINT(2) DEFAULT NULL,
    JOB_DATA BLOB,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP),
    INDEX idx_qrtz_t_j (SCHED_NAME, JOB_NAME, JOB_GROUP),
    INDEX idx_qrtz_t_jg (SCHED_NAME, JOB_GROUP),
    INDEX idx_qrtz_t_c (SCHED_NAME, CALENDAR_NAME),
    INDEX idx_qrtz_t_g (SCHED_NAME, TRIGGER_GROUP),
    INDEX idx_qrtz_t_state (SCHED_NAME, TRIGGER_STATE),
    INDEX idx_qrtz_t_n_state (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    INDEX idx_qrtz_t_n_g_state (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    INDEX idx_qrtz_t_next_fire_time (SCHED_NAME, NEXT_FIRE_TIME),
    INDEX idx_qrtz_t_nft_st (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME),
    INDEX idx_qrtz_t_nft_misfire (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME),
    INDEX idx_qrtz_t_nft_st_misfire (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE),
    INDEX idx_qrtz_t_nft_st_misfire_grp (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_SIMPLE_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT(7) NOT NULL,
    REPEAT_INTERVAL BIGINT(12) NOT NULL,
    TIMES_TRIGGERED BIGINT(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_CRON_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(120) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_SIMPROP_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) DEFAULT NULL,
    STR_PROP_2 VARCHAR(512) DEFAULT NULL,
    STR_PROP_3 VARCHAR(512) DEFAULT NULL,
    INT_PROP_1 INT DEFAULT NULL,
    INT_PROP_2 INT DEFAULT NULL,
    LONG_PROP_1 BIGINT DEFAULT NULL,
    LONG_PROP_2 BIGINT DEFAULT NULL,
    DEC_PROP_1 DECIMAL(13,4) DEFAULT NULL,
    DEC_PROP_2 DECIMAL(13,4) DEFAULT NULL,
    BOOL_PROP_1 VARCHAR(1) DEFAULT NULL,
    BOOL_PROP_2 VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_BLOB_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA BLOB,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    INDEX (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_CALENDARS
CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME VARCHAR(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_PAUSED_TRIGGER_GRPS
CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_FIRED_TRIGGERS
CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT(13) NOT NULL,
    SCHED_TIME BIGINT(13) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200) DEFAULT NULL,
    JOB_GROUP VARCHAR(200) DEFAULT NULL,
    IS_NONCONCURRENT VARCHAR(1) DEFAULT NULL,
    REQUESTS_RECOVERY VARCHAR(1) DEFAULT NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID),
    INDEX idx_qrtz_ft_trig_inst_name (SCHED_NAME, INSTANCE_NAME),
    INDEX idx_qrtz_ft_inst_job_req_rcvry (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY),
    INDEX idx_qrtz_ft_j_g (SCHED_NAME, JOB_NAME, JOB_GROUP),
    INDEX idx_qrtz_ft_jg (SCHED_NAME, JOB_GROUP),
    INDEX idx_qrtz_ft_t_g (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    INDEX idx_qrtz_ft_tg (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_SCHEDULER_STATE
CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
    CHECKIN_INTERVAL BIGINT(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: QRTZ_LOCKS
CREATE TABLE IF NOT EXISTS QRTZ_LOCKS (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

